app = 'ml-task-engine'
primary_region = 'lax'

[build]
  dockerfile = 'backend/Dockerfile.worker'
  context= "."
  build-target = ''

[env]
  PYTHONPATH = "/app"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1